parser: "@typescript-eslint/parser"

plugins:
  - '@typescript-eslint'

parserOptions:
  project: './tsconfig.eslint.json'

extends:
  - 'plugin:@typescript-eslint/recommended'

rules:
  '@typescript-eslint/indent':
    - error
    - 2
