name: Node CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: npm ci
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: npm test
      run: npm test
